name: publish gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: 🐝Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 📦Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Build
        run: mkdocs build
      - name: 🚀Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          CLEAN: true
